version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Пробрасываем порт 8080 из контейнера на хост
    volumes:
      - .:/app # Монтируем текущую директорию внутрь контейнера
      - /app/node_modules # Исключаем node_modules из монтирования
    environment:
      - NODE_ENV=development